import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  presets: [
    {
      theme: {
        extend: {
          screens: {
            xs: "480px",
            sm: "640px",
            md: "768px",
            lg: "1024px",
            xl: "1216px",
          },
          colors: {
            transparent: "transparent",
            current: "currentColor",
            black: "#000",
            white: "#fff",
            pink: {
              "50": "#fdf2f8",
              "100": "#fce7f3",
              "200": "#fbcfe8",
              "300": "#f9a8d4",
              "400": "#f472b6",
              "500": "#ec4899",
              "600": "#db2777",
              "700": "#be185d",
              "800": "#9d174d",
              "900": "#831843",
              "950": "#500724",
            },
            gray: {
              "50": "#F5FAF9",
              "100": "#EDF2F1",
              "200": "#D9DEDD",
              "300": "#C7CFCD",
              "400": "#AEB5B4",
              "500": "#929C9A",
              "600": "#7F8786",
              "700": "#646A69",
              "800": "#4C524F",
              "900": "#1D1F1E",
            },
            lime: {
              "50": "#F7FEE7",
              "100": "#ECFCCB",
              "200": "#D9F99D",
              "300": "#BEF264",
              "400": "#A3E635",
              "500": "#BEF264",
              "600": "#65A30D",
              "700": "#4D7C0F",
              "800": "#365314",
              "900": "#1A2E05",
            },
            teal: {
              "50": "#ECFDF5",
              "100": "#D1FAE5",
              "200": "#A7F3D0",
              "300": "#6EE7B7",
              "400": "#34D399",
              "500": "#10B981",
              "600": "#059669",
              "700": "#065F46",
              "800": "#064E3B",
              "900": "#022C22",
            },
            red: {
              "50": "#FEF2F2",
              "100": "#FEE2E2",
              "200": "#FECACA",
              "300": "#FCA5A5",
              "400": "#F87171",
              "500": "#EF4444",
              "600": "#DC2626",
              "700": "#B91C1C",
              "800": "#991B1B",
              "900": "#7F1D1D",
            },
            orange: {
              "50": "#FFF7ED",
              "100": "#FFEDD5",
              "200": "#FED7AA",
              "300": "#FDBA74",
              "400": "#FB923C",
              "500": "#F97316",
              "600": "#EA580C",
              "700": "#C2410C",
              "800": "#9A3412",
              "900": "#7C2D12",
            },
            green: {
              "50": "#F0FDF4",
              "100": "#DCFCE7",
              "200": "#BBF7D0",
              "300": "#86EFAC",
              "400": "#4ADE80",
              "500": "#22C55E",
              "600": "#16A34A",
              "700": "#15803D",
              "800": "#166534",
              "900": "#14532D",
            },
            blue: {
              "50": "#EFF6FF",
              "100": "#DBEAFE",
              "200": "#BFDBFE",
              "300": "#93C5FD",
              "400": "#60A5FA",
              "500": "#3B82F6",
              "600": "#2563EB",
              "700": "#1D4ED8",
              "800": "#1E40AF",
              "900": "#1E3A8A",
            },
          },
          spacing: {
            "0": "0px",
            "1": "0.25rem",
            "2": "0.5rem",
            "3": "0.75rem",
            "4": "1rem",
            "5": "1.25rem",
            "6": "1.5rem",
            "7": "1.75rem",
            "8": "2rem",
            "9": "2.25rem",
            "10": "2.5rem",
            "11": "2.75rem",
            "12": "3rem",
            "14": "3.5rem",
            "16": "4rem",
            "18": "4.5rem",
            "20": "5rem",
            "24": "6rem",
            "27": "6.75rem",
            "28": "7rem",
            "32": "8rem",
            "34": "8.5rem",
            "36": "9rem",
            "40": "10rem",
            "44": "11rem",
            "48": "12rem",
            "52": "13rem",
            "56": "14rem",
            "60": "15rem",
            "62": "15.5rem",
            "64": "16rem",
            "72": "18rem",
            "74": "18.5rem",
            "80": "20rem",
            "87": "21.75rem",
            "96": "24rem",
            "100": "25rem",
            "112": "28rem",
            "116": "29rem",
            "128": "32rem",
            "135": "33.75rem",
            "148": "37rem",
            "160": "40rem",
            "170": "42.5rem",
            "186": "46.5rem",
            "235": "58.75rem",
            "470": "117.5rem",
            px: "1px",
            "0.5": "0.125rem",
            "1.5": "0.375rem",
            "2.5": "0.625rem",
            "3.5": "0.875rem",
          },
          animation: {
            none: "none",
            spin: "spin 1s linear infinite",
            spinSlow: "spin 6s linear infinite",
            spinStar: "spin 16s linear infinite",
            ping: "ping 1s cubic-bezier(0, 0, 0.2, 1) infinite",
            pulse: "pulse 2s cubic-bezier(0.4, 0, 0.6, 1) infinite",
            bounce: "bounce 1s infinite",
          },
          backgroundColor: (theme: any) => ({
            ...theme("colors"),
            body: "#fff",
          }),
          blur: {
            none: "0px",
            DEFAULT: "20px",
            sm: "4px",
            md: "16px",
            lg: "24px",
            xl: "28px",
            "2xl": "40px",
            "3xl": "64px",
            "4xl": "150px",
          },
          backdropBlur: (theme: any) => theme("blur"),
          backgroundImage: {
            none: "none",
            "gradient-to-t": "linear-gradient(to top, var(--tw-gradient-stops))",
            "gradient-to-tr":
              "linear-gradient(to top right, var(--tw-gradient-stops))",
            "gradient-to-r":
              "linear-gradient(to right, var(--tw-gradient-stops))",
            "gradient-to-br":
              "linear-gradient(to bottom right, var(--tw-gradient-stops))",
            "gradient-to-b":
              "linear-gradient(to bottom, var(--tw-gradient-stops))",
            "gradient-to-bl":
              "linear-gradient(to bottom left, var(--tw-gradient-stops))",
            "gradient-to-l":
              "linear-gradient(to left, var(--tw-gradient-stops))",
            "gradient-to-tl":
              "linear-gradient(to top left, var(--tw-gradient-stops))",
            radial: "radial-gradient(var(--tw-gradient-stops))",
          },
          borderColor: (theme: any) => ({
            ...theme("colors"),
            DEFAULT: theme("colors.gray.200", "currentColor"),
          }),
          borderRadius: {
            none: "0px",
            sm: "0.125rem",
            DEFAULT: "0.25rem",
            md: "0.375rem",
            lg: "0.5rem",
            xl: "0.75rem",
            "2xl": "1rem",
            "3xl": "1.25rem",
            "4xl": "1.875rem",
            "5xl": "5rem",
            full: "9999px",
          },
          borderWidth: {
            "0": "0px",
            "2": "2px",
            "4": "4px",
            "8": "8px",
            DEFAULT: "1px",
          },
          boxShadow: {
            sm: "0 1px 2px 0 rgb(0 0 0 / 0.05)",
            DEFAULT:
              "0px 0px 0px 1px rgb(0 0 0 / 0.1), 0 1px 2px -1px rgb(0 0 0 / 0.1)",
            md: " 0px 0px 0px 1px rgba(18, 105, 63, 0.08), 0px 1px 2px 0px rgba(87, 92, 86, 0.16), 0px 24px 24px -12px rgba(54, 74, 54, 0.06)",
            lg: "0 10px 15px -3px rgb(0 0 0 / 0.1), 0 4px 6px -4px rgb(0 0 0 / 0.1)",
            xl: "0 20px 25px -5px rgb(0 0 0 / 0.1), 0 8px 10px -6px rgb(0 0 0 / 0.1)",
            "2xl": "0 25px 50px -12px rgb(0 0 0 / 0.25)",
            inner: "inset 0 2px 4px 0 rgb(0 0 0 / 0.05)",
            none: "none",
          },
          fontFamily: {
            body: [
              "Figtree",
              "ui-sans-serif",
              "system-ui",
              "-apple-system",
              "BlinkMacSystemFont",
              '"Segoe UI"',
              "Roboto",
              '"Helvetica Neue"',
              "Arial",
              '"Noto Sans"',
              "sans-serif",
              '"Apple Color Emoji"',
              '"Segoe UI Emoji"',
              '"Segoe UI Symbol"',
              '"Noto Color Emoji"',
            ],
            heading: [
              "Figtree",
              "ui-sans-serif",
              "system-ui",
              "-apple-system",
              "BlinkMacSystemFont",
              '"Segoe UI"',
              "Roboto",
              '"Helvetica Neue"',
              "Arial",
              '"Noto Sans"',
              "sans-serif",
              '"Apple Color Emoji"',
              '"Segoe UI Emoji"',
              '"Segoe UI Symbol"',
              '"Noto Color Emoji"',
            ],
            sans: [
              "Figtree",
              "DM Sans",
              "ui-sans-serif",
              "system-ui",
              "-apple-system",
              "BlinkMacSystemFont",
              '"Segoe UI"',
              "Roboto",
              '"Helvetica Neue"',
              "Arial",
              '"Noto Sans"',
              "sans-serif",
              '"Apple Color Emoji"',
              '"Segoe UI Emoji"',
              '"Segoe UI Symbol"',
              '"Noto Color Emoji"',
            ],
            serif: [
              "ui-serif",
              "Georgia",
              "Cambria",
              '"Times New Roman"',
              "Times",
              "serif",
            ],
            mono: [
              "ui-monospace",
              "SFMono-Regular",
              "Menlo",
              "Monaco",
              "Consolas",
              '"Liberation Mono"',
              '"Courier New"',
              "monospace",
            ],
          },
          fontSize: {
            xs: [
              "0.75rem",
              {
                lineHeight: "1.5",
              },
            ],
            sm: [
              "0.875rem",
              {
                lineHeight: "1.25",
              },
            ],
            base: [
              "1rem",
              {
                lineHeight: "1.5",
              },
            ],
            lg: [
              "1.125rem",
              {
                lineHeight: "1.5",
              },
            ],
            xl: [
              "1.25rem",
              {
                lineHeight: "1.5",
              },
            ],
            "2xl": [
              "1.5rem",
              {
                lineHeight: "1.3",
              },
            ],
            "3xl": [
              "1.875rem",
              {
                lineHeight: "1.3",
              },
            ],
            "4xl": [
              "2.25rem",
              {
                lineHeight: "1.2",
              },
            ],
            "5xl": [
              "3rem",
              {
                lineHeight: "0.95",
              },
            ],
            "6xl": [
              "3.75rem",
              {
                lineHeight: "0.95",
              },
            ],
            "7xl": [
              "4.5rem",
              {
                lineHeight: "0.95",
              },
            ],
            "8xl": [
              "6rem",
              {
                lineHeight: "0.95",
              },
            ],
            "9xl": [
              "10.75rem",
              {
                lineHeight: "1",
              },
            ],
            "10xl": [
              "14rem",
              {
                lineHeight: "1",
              },
            ],
          },
          fontWeight: {
            thin: "100",
            extralight: "200",
            light: "300",
            normal: "400",
            medium: "500",
            semibold: "600",
            bold: "700",
            extrabold: "800",
            black: "900",
          },
          letterSpacing: {
            tighter: "-0.05em",
            tight: "-0.025em",
            normal: "0em",
            wide: "0.025em",
            wider: "0.05em",
            widest: "0.1em",
            xs: "-1.85px",
            sm: "-2.25px",
          },
          lineHeight: {
            "3": ".75rem",
            "4": "1rem",
            "5": "1.25rem",
            "6": "1.5rem",
            "7": "1.75rem",
            "8": "2rem",
            "9": "2.25rem",
            "10": "2.5rem",
            none: "1",
            tight: "1.25",
            snug: "1.375",
            normal: "1.5",
            relaxed: "1.625",
            loose: "2",
          },
          maxWidth: (theme: any, { breakpoints }: any) => ({
            none: "none",
            0: "0rem",
            xs: "20rem",
            sm: "24rem",
            md: "28rem",
            lg: "32rem",
            xl: "36rem",
            "2xl": "42rem",
            "3xl": "48rem",
            "4xl": "50rem",
            "5xl": "56rem",
            "6xl": "63rem",
            "7xl": "72rem",
            "8xl": "76rem",
            full: "100%",
            min: "min-content",
            max: "max-content",
            prose: "65ch",
            ...breakpoints(theme("screens")),
          }),
          outline: {
            none: ["2px solid transparent", "2px"],
            white: ["2px dotted white", "2px"],
            black: ["2px dotted black", "2px"],
            lime: ["2px solid #BEF264", "2px"],
          },
          textColor: (theme: any) => ({
            ...theme("colors"),
            body: "#1D1F1E",
          }),
          transitionDuration: {
            "75": "75ms",
            "100": "100ms",
            "150": "150ms",
            "200": "200ms",
            "300": "300ms",
            "500": "500ms",
            "700": "700ms",
            "1000": "1000ms",
            DEFAULT: "150ms",
          },
          transitionProperty: {
            none: "none",
            all: "all",
            DEFAULT:
              "background-color, border-color, color, fill, stroke, opacity, box-shadow, transform, filter, backdrop-filter",
            colors: "background-color, border-color, color, fill, stroke",
            opacity: "opacity",
            shadow: "box-shadow",
            transform: "transform",
          },
          transitionTimingFunction: {
            DEFAULT: "cubic-bezier(0.4, 0, 0.2, 1)",
            linear: "linear",
            in: "cubic-bezier(0.4, 0, 1, 1)",
            out: "cubic-bezier(0, 0, 0.2, 1)",
            "in-out": "cubic-bezier(0.4, 0, 0.2, 1)",
          },
        },
      },
    },
  ],
  theme: {
    extend: {},
  },
};
export default config;


